// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IFaSolidThumbtack: typeof import('~icons/fa-solid/thumbtack')['default']
    IMdiChartPie: typeof import('~icons/mdi/chart-pie')['default']
    IMdiComment: typeof import('~icons/mdi/comment')['default']
    IMdiEye: typeof import('~icons/mdi/eye')['default']
    IMdiFire: typeof import('~icons/mdi/fire')['default']
    IMdiHeart: typeof import('~icons/mdi/heart')['default']
    IMdiLock: typeof import('~icons/mdi/lock')['default']
    IMdiReply: typeof import('~icons/mdi/reply')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
