# https://pnpm.io/settings

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  lightningcss: true
  rolldown: true
  unrs-resolver: true
patchedDependencies:
  quasar@2.24.0: patches/quasar@2.24.0.patch
