export { default as HomeFilled } from '@vicons/material/es/HomeFilled'
export { default as ForumFilled } from '@vicons/material/es/ForumFilled'
export { default as AnnouncementFilled } from '@vicons/material/es/AnnouncementFilled'
export { default as MessageFilled } from '@vicons/material/es/MessageFilled'
export { default as InfoFilled } from '@vicons/material/es/InfoFilled'
export { default as KeyboardArrowRightFilled } from '@vicons/material/es/KeyboardArrowRightFilled'
export { default as SaveFilled } from '@vicons/material/es/SaveFilled'
