export {
  mdiMagnify,
  mdiArrowLeft,
  mdiArrowRight,
  mdiMenu,
  mdiHome,
  mdiInformation,
  mdiBullhorn,
  mdiBook,
  mdiForum,
  mdiBroadcast,
  mdiBroadcastOff,
  mdiBell,
  mdiHistory,
  mdiMessageText,
  mdiCog,
  mdiHelpCircle,
  mdiMessageAlert,
  mdiAccountMultiple
} from '@mdi/js'
