export default {
  name: 'mdi-js',
  type: {
    positive: 'mdiCheckCircle',
    negative: 'mdiAlert',
    info: 'mdiInformation',
    warning: 'mdiExclamation',
  },
  arrow: {
    up: 'mdiArrowUp',
    right: 'mdiArrowRight',
    down: 'mdiArrowDown',
    left: 'mdiArrowLeft',
    dropdown: 'mdiMenuDown',
  },
  chevron: {
    left: 'mdiArrowLeft',
    right: 'mdiArrowRight',
  },
  colorPicker: {
    spectrum: 'mdiGradientVertical',
    tune: 'mdiTune',
    palette: 'mdiPalette',
  },
  pullToRefresh: {
    icon: 'mdiRefresh',
  },
  carousel: {
    left: 'mdiArrowLeft',
    right: 'mdiArrowRight',
    up: 'mdiChevronUp',
    down: 'mdiChevronDown',
    navigationIcon: 'mdi-circle',
  },
  chip: {
    remove: 'mdi-close-circle',
    selected: 'mdi-check',
  },
  datetime: {
    arrowLeft: 'mdiArrowLeft',
    arrowRight: 'mdiArrowRight',
    now: 'mdi-clock-outline',
    today: 'mdi-calendar-today',
  },
  editor: {
    bold: 'mdiFormatBold',
    italic: 'mdiFormatItalic',
    strikethrough: 'mdiFormatStrikethrough',
    underline: 'mdiFormatUnderline',
    unorderedList: 'mdiFormatListBulleted',
    orderedList: 'mdiFormatListNumbered',
    subscript: 'mdiFormatSubscript',
    superscript: 'mdiFormatSuperscript',
    hyperlink: 'mdiLink',
    toggleFullscreen: 'mdiFullscreen',
    quote: 'mdiFormatQuoteClose',
    left: 'mdiFormatAlignLeft',
    center: 'mdiFormatAlignCenter',
    right: 'mdiFormatAlignRight',
    justify: 'mdiFormatAlignJustify',
    print: 'mdiPrinter',
    outdent: 'mdiFormatIndentDecrease',
    indent: 'mdiFormatIndentIncrease',
    removeFormat: 'mdiFormatClear',
    formatting: 'mdiFormatColorText',
    fontSize: 'mdiFormatSize',
    align: 'mdiFormatAlignLeft',
    hr: 'mdiMinus',
    undo: 'mdiUndo',
    redo: 'mdiRedo',
    heading: 'mdiFormatSize',
    heading1: 'mdiFormatHeader1',
    heading2: 'mdiFormatHeader2',
    heading3: 'mdiFormatHeader3',
    heading4: 'mdiFormatHeader4',
    heading5: 'mdiFormatHeader5',
    heading6: 'mdiFormatHeader6',
    code: 'mdiCodeTags',
    size: 'mdiFormatSize',
    size1: 'mdiNumeric1Box',
    size2: 'mdiNumeric2Box',
    size3: 'mdiNumeric3Box',
    size4: 'mdiNumeric4Box',
    size5: 'mdiNumeric5Box',
    size6: 'mdiNumeric6Box',
    size7: 'mdiNumeric7Box',
    font: 'mdiFormatFont',
    viewSource: 'mdiCodeTags',
  },
  expansionItem: {
    icon: 'mdiChevronDown',
    denseIcon: 'mdiMenuDown',
  },
  fab: {
    icon: 'mdiPlus',
    activeIcon: 'mdiClose',
  },
  field: {
    clear: 'mdiCloseCircle',
    error: 'mdi-alert-circle',
  },
  pagination: {
    first: 'mdi-chevron-double-left',
    prev: 'mdiArrowLeft',
    next: 'mdiArrowRight',
    last: 'mdi-chevron-double-right',
  },
  rating: {
    icon: 'mdi-star',
  },
  stepper: {
    done: 'mdi-check',
    active: 'mdi-pencil',
    error: 'mdi-alert',
  },
  tabs: {
    left: 'mdiArrowLeft',
    right: 'mdiArrowRight',
    up: 'mdi-chevron-up',
    down: 'mdi-chevron-down',
  },
  table: {
    arrowUp: 'mdi-arrow-up',
    warning: 'mdi-alert',
    firstPage: 'mdi-chevron-double-left',
    prevPage: 'mdiArrowLeft',
    nextPage: 'mdiArrowRight',
    lastPage: 'mdi-chevron-double-right',
  },
  tree: {
    icon: 'mdi-play',
  },
  uploader: {
    done: 'mdiCheck',
    clear: 'mdiClose',
    add: 'mdiPlusBox',
    upload: 'mdiCloudUpload',
    removeQueue: 'mdiNotificationClearAll',
    removeUploaded: 'mdiCheckAll',
  },
}
