name: Build CI For Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: 设置权限
        run: chmod -R 755 ./src-capacitor/android/

      - name: 设置 JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: 设置 Android SDK
        uses: android-actions/setup-android@v2

      - name: 设置环境变量
        run: export PATH=$PATH:$ANDROID_SDK_ROOT/tools; PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools

      - name: 设置 Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'

      - name: 安装依赖
        run: npm i

      - name: 构建 Android
        run: npm run build:android

      - name: 上传 Apk
        uses: actions/upload-artifact@v3
        with:
          name: app-release-unsigned
          path: ./dist/capacitor/android/apk/release/app-release-unsigned.apk